airflow:
  etl_dag:
    schedule: "@daily"
    date_ranges:
      start: "2017-01-01"  # YYYY-MM-DD format
      end: "2017-12-31"
    coins:
      - bitcoin
    raw_data_path: "/app/data/raw/"
    processed_data_path: "/app/data/processed/"
  
  model_dag:
    schedule: "0 0 1 */6 *"  # Weekly on Sunday at midnight
    coins:
      - bitcoin
    model_path: "/app/data/models/"
    hyperparams: 
      n_estimators: [50, 150]
      max_depth: [5, 10]
      min_samples_split: [5, 10]
      min_samples_leaf: [2, 4]
      max_features: ['log2', 0.5]
  
    evaluation_metrics: ['mae', 'rmse', 'r2']
    
  monitor_dag:
    schedule: "0 0 * * *"  # Daily at midnight
    coins:
      - bitcoin
    metrics_path: '/app/data/processed/metrics/'
    drift_threshold: 0.5
    comparison_window: 30
    alert_emails: ["muddalasatyanarayana96@gmail.com"]


